version: '3.11'

services:

  redis:
    image: redis
    ports:
      - '6379:6379'

  app:
    build: .
    tty: true
    env_file:
      - .env
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && python manage.py csu
      && python manage.py runserver"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d postgres -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app
      - db
    restart: on-failure

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l info -S django
    depends_on:
      - redis
      - app
      - db
    restart: on-failure


volumes:
  pg_data:


